### ISSUE TITLE
App segfaults if a backend is unavailable

### ISSUE THREAD

**Issue by neufeldtech** [swalberg/promproxy#2]
Hi,
When using `promproxy`, I've discovered that the app throws a segfault similar to the one below if one of the backends becomes unavailable (is down).

```
Oct 27 12:26:44 dc1prd promproxy[15839]: 2018/10/27 12:26:44 Received: /api/v1/series?match[]=wmi_system_system_up_time&start=1540657605&end=1540668405
Oct 27 12:26:44 dc1prd promproxy[15839]: 2018/10/27 12:26:44 Getting http://dc1prd.example.com:9090/api/v1/series?match[]=wmi_system_system_up_time&start=1540657605&end
Oct 27 12:26:44 dc1prd promproxy[15839]: 2018/10/27 12:26:44 Getting http://dc1stg.example.com:9090/api/v1/series?match[]=wmi_system_system_up_time&start=1540657605&end
Oct 27 12:26:44 dc1prd promproxy[15839]: 2018/10/27 12:26:44 Getting http://dc1stg.example.com:9090/api/v1/series?match[]=wmi_system_system_up_time&start=1540657605&end
Oct 27 12:26:44 dc1prd promproxy[15839]: 2018/10/27 12:26:44 Getting http://dc1prd.example.com:9090/api/v1/series?match[]=wmi_system_system_up_time&start=1540657605&end
Oct 27 12:26:44 dc1prd promproxy[15839]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 27 12:26:44 dc1prd promproxy[15839]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x64e644]
Oct 27 12:26:44 dc1prd promproxy[15839]: goroutine 21 [running]:
Oct 27 12:26:44 dc1prd promproxy[15839]: main.DoHTTPGet(0xc420114100, 0x73, 0xc420110180)
Oct 27 12:26:44 dc1prd promproxy[15839]: /root/go/src/github.com/swalberg/promproxy/app.go:78 +0xf4
Oct 27 12:26:44 dc1prd promproxy[15839]: created by main.proxyHandler
Oct 27 12:26:44 dc1prd promproxy[15839]: /root/go/src/github.com/swalberg/promproxy/app.go:59 +0x2ef
Oct 27 12:26:44 dc1prd systemd[1]: promproxy.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 27 12:26:44 dc1prd systemd[1]: Unit promproxy.service entered failed state.
Oct 27 12:26:44 dc1prd systemd[1]: promproxy.service failed.
Oct 27 12:26:45 dc1prd systemd[1]: promproxy.service holdoff time over, scheduling restart.
Oct 27 12:26:45 dc1prd systemd[1]: Started Prometheus Proxy.
Oct 27 12:26:45 dc1prd systemd[1]: Starting Prometheus Proxy...
```

**Comment by swalberg** [comment]
Thanks for the bug report. Will try and reproduce locally!
